# Generated by Django 5.2.1 on 2025-05-24 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytwitter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertwitter',
            old_name='created_at',
            new_name='create_at',
        ),
    ]
